#!/bin/bash
# ─────────────────────────────────────────────────────────────────
# TESTING HARNESS ONLY - NEVER SHIP IN AN INFERNODE RELEASE.
# ─────────────────────────────────────────────────────────────────
#
# serve-agent.sh — Launch the headless agent gateway for the external
# evaluation harness. Exports /mnt/llm (port 5640) and /mnt/ui (port 5641),
# both bound to 127.0.0.1, with Inferno Ed25519 keyring authentication.
#
# Reuses the serve-llm keyfile at ~/.infernode/lib/keyring/serve-llm,
# generated by `serve-llm.sh --gen-key`. The harness operator and the
# LLM gateway operator share one trust boundary; if you need to separate
# them, generate two keyfiles and edit SERVE_LLM_KEY below.
#
# Usage:
#   serve-agent.sh                  # localhost, keyring auth (default)
#   serve-agent.sh --anon-lan       # localhost, no authentication (debug only)
#   serve-agent.sh --help
#
# Key generation: this script does not generate keys. Run
#   serve-llm.sh --gen-key
# once to produce the shared keyfile.

set -euo pipefail

HARNESS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INFERNODE_ROOT="${INFERNODE_ROOT:-$HARNESS_ROOT/vendor/infernode}"

case "$(uname -s)" in
	Linux)   EMU="$INFERNODE_ROOT/emu/Linux/o.emu" ;;
	Darwin)  EMU="$INFERNODE_ROOT/emu/MacOSX/o.emu" ;;
	*)       echo "serve-agent: unsupported platform $(uname -s)" >&2; exit 1 ;;
esac

PROFILE_REL="tmp/infernode-escape-room/serve-agent"
PROFILE_SOURCE="$HARNESS_ROOT/guest/serve-agent"
PROFILE_HOST="$INFERNODE_ROOT/$PROFILE_REL"
PROFILE_INF="/$PROFILE_REL"

# Shared keyfile — same path serve-llm.sh writes / reads.
KEY_HOSTPATH="${HOME}/.infernode/lib/keyring/serve-llm"
KEY_INFPATH="/lib/keyring/serve-llm"

print_help() {
	sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'
}

LISTEN_MODE="keyring"
for arg in "$@"; do
	case "$arg" in
		--anon-lan) LISTEN_MODE="anon" ;;
		-h|--help)  print_help; exit 0 ;;
		*) echo "serve-agent: unknown arg: $arg (try --help)" >&2; exit 2 ;;
	esac
done

[ -x "$EMU" ]             || { echo "serve-agent: emu missing at $EMU" >&2; exit 1; }
[ -f "$PROFILE_SOURCE" ]  || { echo "serve-agent: profile missing at $PROFILE_SOURCE" >&2; exit 1; }
mkdir -p "$(dirname "$PROFILE_HOST")"
cp "$PROFILE_SOURCE" "$PROFILE_HOST"
chmod 700 "$PROFILE_HOST"

if [ "$LISTEN_MODE" = "keyring" ] && [ ! -s "$KEY_HOSTPATH" ]; then
	cat >&2 <<EOF
serve-agent: ERROR no keyfile at $KEY_HOSTPATH

  serve-agent reuses the serve-llm keyfile. Generate it with:
    $INFERNODE_ROOT/serve-llm.sh --gen-key

  Or to listen without authentication (loopback only, but still
  unauthenticated — debug use):
    $0 --anon-lan
EOF
	exit 1
fi

cnsa_truthy() {
	case "${1:-}" in
		""|0*|n*|N*) return 1 ;;
		*)           return 0 ;;
	esac
}
if cnsa_truthy "${CNSAMODE:-}"; then CNSAMODE=1; else CNSAMODE=0; fi
export CNSAMODE

export SERVE_LLM_AUTH="$LISTEN_MODE"
export SERVE_LLM_KEY="$KEY_INFPATH"

cat >&2 <<EOF
serve-agent: $(date -Iseconds) starting
  emu     = $EMU
  root    = $INFERNODE_ROOT
  profile = $PROFILE_INF
  listen  = $LISTEN_MODE (loopback only)
  cnsa    = $CNSAMODE (1 = ML-KEM-1024 + ML-DSA-87; 0 = ML-KEM-768)
  /mnt/llm  = tcp!127.0.0.1!5640
  /mnt/ui   = tcp!127.0.0.1!5641
  keyfile = $KEY_HOSTPATH (in-emu: $KEY_INFPATH)
EOF

exec "$EMU" -c1 "-r$INFERNODE_ROOT" sh "$PROFILE_INF"
